/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinematickets.frame;

import cinematickets.CinemaTickets;

/**
 *
 * @author AlexVB
 */
public class MainFrame extends javax.swing.JFrame {
 // Variable estática que podría representar la instancia principal del sistema
 // Instancias de las diferentes pestañas del sistema
    ClientsTab clientsTab = new ClientsTab();       // Pestaña para gestionar clientes
    FunctionsTab functionsTab = new FunctionsTab(); // Pestaña para gestionar funciones (proyecciones)
    MoviesTab moviesTab = new MoviesTab();          // Pestaña para gestionar películas
    RoomsTab roomsTab = new RoomsTab();             // Pestaña para gestionar salas
    TicketsTab ticketsTab = new TicketsTab();       // Pestaña para gestionar tickets


      /**
     * Creates new form MainFrame
     * Constructor del marco principal. Se encarga de inicializar la interfaz gráfica
     * y agregar las pestañas correspondientes al tabbedPane.
     */
    public MainFrame() {

        initComponents();

        tabbedPane.add("Peliculas", moviesTab);
        tabbedPane.add("Salas", roomsTab);
        tabbedPane.add("Funciones", functionsTab);
        tabbedPane.add("Clientes", clientsTab);
        tabbedPane.add("Tickets", ticketsTab);

        updateStatuses();
    }

    private void updateStatuses() {
        clientsTab.updateState();    // Actualiza la información mostrada en la pestaña de clientes
        functionsTab.updateState();  // Actualiza la información de funciones disponibles
        moviesTab.updateState();     // Actualiza la lista o información de películas
        roomsTab.updateState();      // Actualiza la visualización de las salas
        ticketsTab.updateState();    // Refresca la información de tickets emitidos o disponibles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        updateStatuses();
    }//GEN-LAST:event_tabbedPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
